[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "The Safe Network Faucet"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_faucet"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.3.39"

[features]
default = []
distribition = ["bitcoin", "minreq"]

[[bin]]
path="src/main.rs"
name="faucet"

[dependencies]
bitcoin = { version = "0.31.0", optional = true}
bls = { package = "blsttc", version = "8.0.1" }
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = "0.6.2"
dirs-next = "~2.0.0"
indicatif = { version = "0.17.5", features = ["tokio"] }
minreq = { version = "2.11.0", features = ["https-rustls"], optional = true}
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sn_client = { path = "../sn_client", version = "0.103.1" }
sn_logging = { path = "../sn_logging", version = "0.2.18" }
sn_peers_acquisition = { path = "../sn_peers_acquisition", version = "0.2.5" }
sn_transfers = { path = "../sn_transfers", version = "0.15.0" }
tiny_http = { version="0.12", features = ["ssl-rustls"] }
tokio = { version = "1.32.0", features = ["parking_lot", "rt"] }
tracing = { version = "~0.1.26" }
tracing-core = "0.1.30"

[lints]
workspace = true
