[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "The Safe Network Faucet"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_faucet"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.58"

[features]
# required to pass on flag to node builds
quic = ["sn_client/quic"]

[[bin]]
path="src/main.rs"
name="faucet"

[dependencies]
bls = { package = "blsttc", version = "8.0.1" }
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = "0.6.2"
dirs-next = "~2.0.0"
sn_client = { path = "../sn_client", version = "0.99.1" }
sn_logging = { path = "../sn_logging", version = "0.2.15" }
sn_peers_acquisition = { path = "../sn_peers_acquisition", version = "0.1.11" }
sn_transfers = { path = "../sn_transfers", version = "0.14.24" }
tiny_http = { version="0.12", features = ["ssl-rustls"] }
tokio = { version = "1.32.0", features = ["parking_lot", "rt"] }
tracing = { version = "~0.1.26" }
tracing-core = "0.1.30"
