[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Peers Acquisition"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_peers_acquisition"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.2.10"

[features]
local-discovery = []
network-contacts = ["reqwest", "tokio", "url"]
websockets = []

[dependencies]
clap = { version = "4.2.1", features = ["derive", "env"] }
lazy_static = "~1.4.0"
libp2p = { version="0.53", features = [] }
rand = "0.8.5"
reqwest = { version="0.12.2", default-features=false, features = ["rustls-tls"], optional = true }
sn_protocol = { path = "../sn_protocol", version = "0.16.3" }
thiserror = "1.0.23"
tokio = { version = "1.32.0", optional = true, default-features = false}
tracing = { version = "~0.1.26" }
url = { version = "2.4.0", optional = true }

[lints]
workspace = true
