[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Peers Acquisition"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_peers_acquisition"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.1"

[features]
default=[]
local-discovery=[]

[dependencies]
clap = { version = "4.2.1", features = ["derive", "env"] }
eyre = "0.6.8"
libp2p = { path="../../rust-libp2p/libp2p", version="0.52", features = [] }
tracing = { version = "~0.1.26" }
