[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network AutoNAT probing"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_nat_detection"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.0"

[[bin]]
name = "detect-nat"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
clap = { version = "4.5.4", features = ["derive"] }
futures = "~0.3.13"
libp2p = { version = "0.53", features = ["tokio", "tcp", "noise", "yamux", "autonat", "identify", "macros"] }
tracing = { version = "~0.1.26" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

sn_networking = { path = "../sn_networking", version = "0.15.2" }
clap-verbosity-flag = "2.2.0"
tracing-log = "0.2.0"

[lints]
workspace = true
