[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Test utilities shared between crates"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "test-utils"
readme = "README.md"
repository = "https://github.com/maidsafe/autonomi"
version = "0.4.20"

[dependencies]
ant-bootstrap = { path = "../ant-bootstrap", version = "0.2.3" }
ant-node = { version = "0.4.0", path = "../ant-node" }
autonomi = { version = "0.5.0", path = "../autonomi" }
bytes = { version = "1.0.1", features = ["serde"] }
color-eyre = "0.6.3"
dirs-next = "~2.0.0"
evmlib = { path = "../evmlib", version = "0.4.2" }
libp2p = { version = "0.56.0", features = ["identify", "kad"] }
rand = "0.8.5"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0"
