[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Auditor"
name = "sn_auditor"
version = "0.1.7"
edition = "2021"
homepage = "https://maidsafe.net"
repository = "https://github.com/maidsafe/safe_network"
license = "GPL-3.0"
readme = "README.md"

[features]
default = []
local-discovery=["sn_client/local-discovery", "sn_peers_acquisition/local-discovery"]
network-contacts = ["sn_peers_acquisition/network-contacts"]
open-metrics = ["sn_client/open-metrics"]
websockets = ["sn_client/websockets"]

[dependencies]
bls = { package = "blsttc", version = "8.0.1" }
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = "~0.6"
dirs-next = "~2.0.0"
graphviz-rust = "0.9.0"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
serde_json = "1.0.108"
sn_client = { path = "../sn_client", version = "0.105.3" }
sn_logging = { path = "../sn_logging", version = "0.2.25" }
sn_peers_acquisition= { path="../sn_peers_acquisition", version = "0.2.10" }
tiny_http = { version="0.12", features = ["ssl-rustls"] }
tracing = { version = "~0.1.26" }
tokio = { version = "1.32.0", features = ["io-util", "macros", "parking_lot", "rt", "sync", "time", "fs"] }
