[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Auditor"
name = "sn_auditor"
version = "0.1.0"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
readme = "README.md"

[features]
default = []
local-discovery=["sn_client/local-discovery", "sn_peers_acquisition/local-discovery"]
network-contacts = ["sn_peers_acquisition/network-contacts"]
open-metrics = ["sn_client/open-metrics"]
websockets = ["sn_client/websockets"]

[dependencies]
bls = { package = "blsttc", version = "8.0.1" }
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = "~0.6"
dirs-next = "~2.0.0"
graphviz-rust = "0.7.1"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
serde_json = "1.0.108"
sn_client = "0.104.31"
sn_peers_acquisition = "0.2.6"
tiny_http = { version="0.12", features = ["ssl-rustls"] }
tokio = { version = "1.32.0", features = ["io-util", "macros", "parking_lot", "rt", "sync", "time", "fs"] }
