[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Transfer Logic"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_transfers"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.16.1"

[dependencies]
bls = { package = "blsttc", version = "8.0.1" }
custom_debug = "~0.5.0"
dirs-next = "~2.0.0"
hex = "~0.4.3"
lazy_static = "~1.4.0"
rand = { version = "~0.8.5", features = ["small_rng"] }
rmp-serde = "1.1.1"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
serde_json = "1.0.108"
thiserror = "1.0.24"
tiny-keccak = { version = "~2.0.2", features = [ "sha3" ] }
tracing = { version = "~0.1.26" }
walkdir = "~2.4.0"
xor_name = "5.0.0"
rayon = "1.8.0"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["macros", "rt"] }
criterion = "0.4.0"
assert_fs = "1.0.0"
eyre = "0.6.8"


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fs2 = "0.4.3"

[target."cfg(unix)".dev-dependencies.pprof]
version = "0.11.0"
features = [ "flamegraph" ]

[[bench]]
name = "reissue"
harness = false

[lints]
workspace = true
