[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Networking Logging"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_logging"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.2.4"

[dependencies]
file-rotate = "0.7.3"
opentelemetry = { version = "0.17", features = ["rt-tokio"], optional = true }
opentelemetry-otlp = { version = "0.10", optional = true }
opentelemetry-semantic-conventions = { version = "0.9.0", optional = true }
rand = { version = "~0.8.5", features = ["small_rng"], optional = true }
serde = { version = "1.0.133", features = [ "derive", "rc" ], optional = true }
serde_json = {version = "1.0", optional = true }
sysinfo = { version = "0.29.0", default-features = false, optional = true }
thiserror = "1.0.23"
tokio = { version = "1.17.0", optional = true }
tracing = { version = "~0.1.26" }
tracing-appender = "~0.2.0"
tracing-core = "0.1.30"
tracing-opentelemetry = { version = "0.17", optional = true }
tracing-subscriber = { version = "0.3.16", features=["json"] }

[features]
otlp = [
    "opentelemetry",
    "opentelemetry-otlp",
    "opentelemetry-semantic-conventions",
    "tracing-opentelemetry",
    "rand/small_rng"
]
test-utils = []
process-metrics = [
    "serde",
    "serde_json",
    "sysinfo",
    "tokio"
]
