[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network CLI"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_cli"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.93.7-alpha.2"

[[bin]]
path = "src/bin/main.rs"
name = "safe"

[lib]
path = "src/lib.rs"
name = "autonomi"

[[bench]]
name = "files"
harness = false

[features]
default = ["metrics"]
distribution = ["base64", "bitcoin"]
local-discovery = [
    "sn_client/local-discovery",
    "sn_peers_acquisition/local-discovery",
]
metrics = ["sn_logging/process-metrics"]
network-contacts = ["sn_peers_acquisition/network-contacts"]
open-metrics = ["sn_client/open-metrics"]

[dependencies]
aes = "0.7.5"
base64 = { version = "0.22.0", optional = true }
bitcoin = { version = "0.31.0", optional = true }
block-modes = "0.8.1"
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
custom_debug = "~0.6.1"
chrono = "~0.4.19"
clap = { version = "4.2.1", features = ["derive"] }
color-eyre = "~0.6"
dialoguer = "~0.11.0"
dirs-next = "~2.0.0"
futures = "~0.3.13"
hex = "~0.4.3"
indicatif = { version = "0.17.5", features = ["tokio"] }
libp2p = { version = "0.53", features = ["identify", "kad"] }
rand = "0.8.5"
rayon = "1.8.0"
reqwest = { version = "0.12.2", default-features = false, features = [
    "rustls-tls-manual-roots",
] }
rmp-serde = "1.1.1"
serde = { version = "1.0.133", features = ["derive"] }
sn_build_info = { path = "../sn_build_info", version = "0.1.8" }
sn_client = { path = "../sn_client", version = "0.107.8-alpha.2" }
sn_logging = { path = "../sn_logging", version = "0.2.28" }
sn_peers_acquisition = { path = "../sn_peers_acquisition", version = "0.3.5-alpha.2" }
sn_protocol = { path = "../sn_protocol", version = "0.17.4" }
tempfile = "3.6.0"
tiny-keccak = "~2.0.2"
tokio = { version = "1.32.0", features = [
    "io-util",
    "macros",
    "parking_lot",
    "rt",
    "sync",
    "time",
    "fs",
] }
tracing = { version = "~0.1.26" }
url = "2.4.0"
walkdir = "~2.5.0"
xor_name = "5.0.0"

[dev-dependencies]
eyre = "0.6.8"
criterion = "0.5.1"
tempfile = "3.6.0"
rand = { version = "~0.8.5", features = ["small_rng"] }
sn_client = { path = "../sn_client", version = "0.107.8-alpha.2", features = [
    "test-utils",
] }

[lints]
workspace = true
