[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network Client"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_client"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.95.22"

[features]
default=[]
local-discovery=["sn_networking/local-discovery"]
open-metrics = ["sn_networking/open-metrics", "prometheus-client"]

[dependencies]
async-trait = "0.1"
bincode = "1.3.1"
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
custom_debug = "~0.5.0"
futures = "~0.3.13"
hex = "~0.4.3"
indicatif = { version = "0.17.5", features = ["tokio"] }
itertools = "~0.11.0"
libp2p = {   version="0.53" ,  features = ["identify"] }
prometheus-client = { version = "0.22", optional = true }
rand = { version = "~0.8.5", features = ["small_rng"] }
rayon = "1.8.0"
self_encryption = "~0.28.5"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
sn_networking = { path = "../sn_networking", version = "0.9.21" }
sn_protocol = { path = "../sn_protocol", version = "0.8.12" }
sn_registers = { path = "../sn_registers", version = "0.3.3" }
sn_transfers = { path = "../sn_transfers", version = "0.14.11" }
tempfile = "3.6.0"
thiserror = "1.0.23"
tiny-keccak = "~2.0.2"
tokio = { version = "1.32.0", features = ["io-util", "macros", "parking_lot", "rt", "sync", "time"] }
tracing = { version = "~0.1.26" }
xor_name = "5.0.0"

[dev-dependencies]
eyre = "0.6.8"
# add rand to libp2p
libp2p-identity = { version="0.2.7", features = ["rand"] }
