[package]
name = "autonomi"
version = "0.1.0"
edition = "2021"

[features]
default = ["fs"]
fs = []
local = ["sn_networking/local-discovery"]

[dependencies]
bip39 = "2.0.0"
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
const-hex = "1.12.0"
evmlib = { path = "../evmlib", version = "0.1" }
libp2p = "0.53"
rand = "0.8.5"
rmp-serde = "1.1.1"
self_encryption = "~0.29.0"
serde = { version = "1.0.133", features = ["derive", "rc"] }
sn_networking = { path = "../sn_networking", version = "0.18.0" }
sn_protocol = { path = "../sn_protocol", version = "0.17.8" }
sn_registers = { path = "../sn_registers", version = "0.3.18" }
sn_evm = { path = "../sn_evm", version = "0.1" }
thiserror = "1.0.23"
tokio = { version = "1.35.0", features = ["sync", "fs"] }
tracing = { version = "~0.1.26" }
walkdir = "2.5.0"
xor_name = "5.0.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
