[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Autonomi client API"
name = "autonomi"
license = "GPL-3.0"
version = "0.1.1"
edition = "2021"
homepage = "https://maidsafe.net"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"

[features]
default = ["data"]
full = ["data", "registers", "vault"]
data = []
vault = ["data"]
files = ["fs", "data"]
fs = ["tokio/fs"]
local = ["sn_networking/local-discovery"]
registers = []

[dependencies]
bip39 = "2.0.0"
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
curv = { version = "0.10.1", package = "sn_curv", default-features = false, features = ["num-bigint"] }
eip2333 = { version = "0.2.1", package = "sn_bls_ckd" }
const-hex = "1.12.0"
evmlib = { path = "../evmlib", version = "0.1" }
hex = "~0.4.3"
libp2p = "0.54.1"
rand = "0.8.5"
rmp-serde = "1.1.1"
self_encryption = "~0.29.0"
serde = { version = "1.0.133", features = ["derive", "rc"] }
sn_networking = { path = "../sn_networking", version = "0.18.3" }
sn_peers_acquisition = { path = "../sn_peers_acquisition", version = "0.5.2" }
sn_protocol = { version = "0.17.10", path = "../sn_protocol" }
sn_registers = { path = "../sn_registers", version = "0.3.20" }
sn_transfers = { path = "../sn_transfers", version = "0.19.2" }
sn_evm = { path = "../sn_evm" }
thiserror = "1.0.23"
tokio = { version = "1.35.0", features = ["sync"] }
tracing = { version = "~0.1.26" }
walkdir = "2.5.0"
xor_name = "5.0.0"
futures = "0.3"  # For asynchronous programming
wasm-bindgen = "0.2"  # For WebAssembly bindings
log = "0.4"  
web-sys = { version = "0.3", features = ["console"] }
wasmtimer = "0.2.0"
console_log = "0.2"

[dev-dependencies]
eyre = "0.6.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wasm-bindgen-test = "0.3.43"
console_error_panic_hook = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# See https://github.com/sebcrozet/instant/blob/7bd13f51f5c930239fddc0476a837870fb239ed7/README.md#using-instant-for-a-wasm-platform-where-performancenow-is-not-available
instant = { version = "0.1", features = [ "wasm-bindgen", "inaccurate" ] }

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
