[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Networking Infrastructure"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_networking"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.4.22"

[features]
default=[]
local-discovery=["libp2p/mdns"]

[dependencies]
async-trait = "0.1"
bytes = { version = "1.0.1", features = ["serde"] }
futures = "~0.3.13"
itertools = "~0.10.1"
custom_debug = "~0.5.0"
libp2p = { version="0.52", features = ["tokio", "dns", "kad", "macros", "request-response", "cbor","identify", "autonat", "noise", "tcp", "yamux"] }
rand = { version = "~0.8.5", features = ["small_rng"] }
rmp-serde = "1.1.1"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
sn_protocol = { path = "../sn_protocol", version = "0.5.2" }
sn_dbc = { version = "19.1.1", features = ["serdes"] }
sn_transfers = { path = "../sn_transfers", version = "0.10.27" }
thiserror = "1.0.23"
tokio = { version = "1.17.0", features = ["fs", "io-util", "macros", "parking_lot", "rt", "sync", "time"] }
tracing = { version = "~0.1.26" }
xor_name = "5.0.0"

[dev-dependencies]
bls = { package = "blsttc", version = "8.0.1" }
quickcheck = "1.0.3"
eyre = "0.6.8"
