name: Node.js (release)
env:
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: '10.13'
permissions:
  contents: write
  id-token: write
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Node.js package to publish'
        required: true
        default: 'autonomi'
        type: choice
        options:
          - autonomi
          - ant-node
jobs:
  build-and-test:
    # Build Node.js bindings for all platforms
    uses: ./.github/workflows/nodejs.yml
  publish:
    defaults:
      run:
        working-directory: ${{ inputs.app_name }}-nodejs
    name: Publish ${{ inputs.app_name }}
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: corepack enable

      - name: Install dependencies
        run: npm install

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./${{ inputs.app_name }}-nodejs/artifacts
          pattern: bindings-*-${{ inputs.app_name }}
      - name: Move artifacts
        run: npm run artifacts
      - name: List packages
        run: ls -R ./npm
        shell: bash
      - name: Publish
        run: |
          npm config set provenance true
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --tag latest --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
