name: Update or Allow PR Base Branch

on:
  pull_request:
    branches: [main]
    types: [opened, edited, reopened]

jobs:
  check-and-update-base:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Update Base Branch
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { issue: { number: prNumber }, repository: { owner: { login: owner }, name: repo } } = context.payload;
            const currentBase = context.payload.pull_request.base.ref;
            const sourceBranch = context.payload.pull_request.head.ref;
            const newBase = 'alpha';
            const allowedSources = ['alpha', 'beta'];

            if (currentBase === 'main' && !allowedSources.includes(sourceBranch)) {
              console.log(`Updating the base of PR #${prNumber} from '${currentBase}' to '${newBase}' because the source branch is '${sourceBranch}'`);
              const response = await github.rest.pulls.update({
                owner,
                repo,
                pull_number: prNumber,
                base: newBase,
              });
              console.log(`Base branch updated to '${newBase}': ${response.data.url}`);
            } else {
              console.log(`No update needed for PR #${prNumber} (source: '${sourceBranch}', base: '${currentBase}')`);
            }
